#=====================CAUTION=======================
# DO NOT DELETE THIS FILE SINCE IT IS PART OF NROBO
# FRAMEWORK AND IT MAY CHANGE IN THE FUTURE UPGRADES
# OF NROBO FRAMEWORK. THUS, TO BE ABLE TO SAFELY UPGRADE
# TO LATEST NROBO VERSION, PLEASE DO NOT DELETE THIS
# FILE OR ALTER ITS LOCATION OR ALTER ITS CONTENT!!!
#===================================================
#
# @author: Panchdev Singh Chauhan
# @email: erpanchdev@gmail.com
####################################################


# Waits

# For future reference. Not used at the moment.
sleep: 1

# Default sleep time. Ex. <Page_object>.wait_for_a_while() will wait for 1 sec if not given arg value.
wait: 1

# default page load timeout time.
timeout: 30

# Default element to be present timeout time.
ele_wait: 3